// Vietnamese translations
export const en = {
  // Common
  common: {
    cancel: 'Hủy bỏ',
    confirm: 'Xác nhận',
    close: 'Đóng',
    back: 'Quay lại',
    save: 'Lưu',
    loading: 'Đang tải...',
    error: 'Lỗi',
    success: 'Thành công',
    gotIt: 'Hiểu rồi',
    maybeLater: 'Để lần sau',
    disabled: 'Tắt',
    ok: 'OK',
    retry: 'Thử lại',
  },

  // Menu items
  menu: {
    menu: 'Menu',
    myBalls: 'Countryballs của tôi',
    shop: 'Cửa hàng',
    items: 'Vật phẩm',
    dex: 'Dex',
    settings: 'Cài đặt',
    tutorials: 'Hướng dẫn',
    recruit: 'Tuyển',
    quests: 'Nhiệm vụ',
    battle: 'Battle', 
  },

  // Game Screen
  gameScreen: {
    myTerritory: 'Vùng lãnh thổ của tôi',
    drag: 'Kéo',
    loadingTerritories: 'Đang tải các vùng lãnh thổ...',
    calibratingLocation: 'Đang hiệu chỉnh vị trí...',
    bagFull: 'Túi đầy',
    bagFullMessage: 'Túi của bạn đã đầy ({current}/{max}). Hãy thu dọn bớt kho lưu trữ trước khi nhận phần thưởng này.',
    goToShop: 'Đi đến cửa hàng',
    noAlliance: 'Không có liên minh',
  },

  // Alliance
  alliance: {
    alliancesLocked: 'Các liên minh bị khóa',
    unlockRequirements: 'Để có thể vào được liên minh, bạn phải đáp ứng những yêu cầu này:',
    reachLevel: 'Đạt cấp độ {level}',
    currentLevel: 'Hiện tại: {level}',
    createAccount: 'Tạo tài khoản',
    guestAccount: 'Tài khoản khách',
    guestInstructions: 'Bạn có thể chuyển đổi tài khoản khách của bạn thành tài khoản thật thông qua',
    settingsSecurity: 'Cài đặt → Bảo mật',
  },

  // Settings
  settings: {
    title: 'Cài đặt',
    backToSettings: 'Quay lại cài đặt',
    // Main menu options
    gameplay: 'Lối chơi',
    gameplayDescription: 'Bản đồ, riêng tư, và cài đặt pin',
    audio: 'Âm thanh',
    audioDescription: 'Nhạc và hiệu ứng âm thanh',
    artistCredits: 'Thông tin họa sĩ',
    artistCreditsDescription: 'Xem thông tin về hình ảnh trò chơi',
    security: 'Bảo mật',
    securityDescription: 'Quản lý các tài khoản được liên kết',
    support: 'Hỗ trợ',
    supportDescription: 'Xem các nguồn hỗ trợ',
    signOut: 'Đăng xuất',
    signOutDescription: 'Đăng xuất khỏi tài khoản',
    // Gameplay settings
    mapSettings: 'Cài đặt bản đồ',
    mapStyle: 'Kiểu bản đồ',
    territoryRenderDistance: 'Khoảng cách hiển thị lãnh thổ',
    territoryRenderHint: 'Giá trị cao hơn thể hiện nhiều lãnh thổ hơn nhưng có thể làm giảm hiệu năng',
    languageSettings: 'Cài đặt ngôn ngữ',
    language: 'Ngôn ngữ',
    privacySettings: 'Cài đặt bảo mật',
    allowPublicInvites: 'Cho phép lời mời công khai',
    fromYourProfile: 'Từ màn hình hồ sơ của bạn',
    batterySettings: 'Cài đặt pin',
    energySaverMode: 'Chế độ tiết kiệm năng lượng',
    energySaverOn: 'Tiết kiệm năng lượng, nhưng được cập nhật ít thường xuyên hơn',
    energySaverOff: 'Trải nghiệm tốt nhất, tiêu tốn nhiều pin hơn',
    // Audio settings
    audioSettings: 'Cài đặt âm thanh',
    gameMusic: 'Âm thanh trò chơi',
    soundEffects: 'Hiệu ứng âm thanh',
    // Support tab
    hereToHelp: "Chúng tôi luôn sẵn sàng hỗ trợ bạn!",
    privacyPolicy: 'Chính sách bảo mật',
    viewPrivacyPolicy: 'Xem chính sách bảo mật của chúng tôi',
    termsOfService: 'Điều khoản dịch vụ',
    viewTermsOfService: 'Xem điều khoản dịch vụ của chúng tôi',
    contactUs: 'Liên hệ với chúng tôi',
    dangerZone: 'Vùng nguy hiểm',
    deleteAccount: 'Xóa tài khoản',
    deleteAccountWarning: 'Thao tác này không thể đảo ngược. Toàn bộ tiến trình và dữ liệu của bạn sẽ bị xóa vĩnh viễn.',
    deleteAccountConfirmTitle: 'Xỏa tài khoản?',
    deleteAccountConfirmMessage: 'Thao tác này không thể đảo ngược. Toàn bộ tiến trình và dữ liệu của bạn sẽ bị xóa vĩnh viễn.',
    deleteAccountTypeConfirm: 'Nhập POLANDBALLGO để xác nhận.',
    deleting: 'Đang xóa...',
    version: 'Phiên bản',
    // Phone linking & Security
    linkPhoneNumber: 'Liên kết số điện thoại',
    chooseUsername: 'Chọn tên',
    chooseYourUsername: 'Chọn tên người dùng của bạn',
    pickUsername: 'Chọn một tên người dùng duy nhất cho tài khoản của bạn',
    usernameRequirements: '3-15 ký tự, không có dấu cách',
    username: 'Tên người dùng',
    confirmUsername: 'Xác nhận tên người dùng',
    enterPhoneNumber: 'Nhập số điện thoại',
    sendVerificationCode: "Chúng tôi sẽ gửi cho bạn mã xác nhận",
    phoneNumber: 'Số điện thoại',
    sendCode: 'Gửi mã',
    sending: 'Đang gửi...',
    enterVerificationCode: 'Nhập mã xác nhận',
    checkSms: 'Kiểm tra tin nhắn SMS của bạn để lấy mã',
    verificationCode: 'Mã xác nhận',
    verify: 'Xác nhận',
    verifyAndLink: 'Xác nhận & Liên kết',
    verifying: 'Đang xác nhận...',
    resendCode: 'Gửi lại mã',
    addAnotherMethod: 'Thêm phương thức khác',
    linkAdditionalWays: 'Liên kết các phương thức đăng nhập khác',
    linkedAccounts: 'Các tài khoản được liên kết',
    linkedAccountsDescription: 'Quản lý các tài khoản đã liên kết của bạn',
    unlink: 'Hủy liên kết',
    unlinking: 'Đang hủy liên kết...',
    unlinkAccount: 'Hủy liên kết tài khoản',
    unlinkWarning: 'Bạn có chắc chắn muốn hủy liên kết tài khoản này không? Bạn có thể liên kết lại sau.',
    securityHeroTitle: 'Không bao giờ mất quyền truy cập vào tài khoản Polandball Go của bạn',
    linkAccountDescription: 'Hãy liên kết ít nhất một tài khoản để bạn có thể khôi phục tiến trình chơi và không bao giờ mất quyền truy cập vào hồ sơ của mình.',
    linked: 'Đã liên kết',
    lastUsed: 'Lần cuối sử dụng',
    iosOnly: 'Chỉ dành cho iOS',
    notAvailable: 'Không có sẵn',
    linkProvider: 'Liên kết {provider}',
    signInWithPhone: 'Đăng nhập với số điện thoại của bạn',
    signInWithApple: 'Đăng nhập với Apple ID của bạn',
    signInWithDiscord: 'Đăng nhập với tài khoản Discord của bạn',
    signInWithFacebook: 'Đăng nhập với tài khoản Facebook của bạn',
    signInWithGoogle: 'Đăng nhập với tài khoản Google của bạn',
    singleMethodWarning: 'Hãy cân nhắc thêm phương thức đăng nhập thứ hai để đảm bảo bạn không bao giờ mất quyền truy cập vào tài khoản của mình.',
  },

  // Daily Rewards Modal
  dailyRewards: {
    // Tabs
    quests: 'Các nhiệm vụ',
    event: 'Sự kiện',
    daily: 'Hằng ngày',
    level: 'Cấp độ',
    achievements: 'Thành tựu',
    // Event UI
    daysLeft: 'Còn {days} ngày nữa',
    soon: 'Sắp ra mắt',
    inDays: 'Trong {days} ngày',
    tier: 'Cấp {number}',
    basic: 'Cơ bản',
    premium: 'Cao cấp',
    eventQuests: 'Các nhiệm vụ sự kiện',
    unlockTierDescription: 'Mở khóa mỗi cấp bằng cách hoàn thành một nhiệm vụ',
    noActiveEvent: 'Không có sự kiện nào đang diễn ra',
    loadingEvent: 'Đang tải sự kiện...',
    // Daily rewards
    loadingDailyRewards: 'Đang tải phần thưởng hàng ngày...',
    dayStreak: '{count} chuỗi ngày',
    collect: 'Thu thập',
    completed: 'Hoàn thành',
    // Goals
    dailyCheckin: 'Check-in hàng ngày',
    dailyCheckinDescription: 'Mở ứng dụng ngày hôm nay',
    walk1km: 'Đi bộ 1 KM',
    walk1kmDescription: 'Đi bộ 1 ki-lo-mét',
    conquerTerritory: 'Chinh phục lãnh thổ',
    conquerTerritoryDescription: 'Chiếm 1 vùng lãnh thổ',
    // Level tasks
    requirements: 'Yêu cầu',
    help: 'Giúp đỡ',
    loadingLevelQuests: 'Đang tải nhiệm vụ cấp độ...',
    maxLevelReached: 'Đã đạt được cấp độ tối đa',
    noLevelQuests: 'Không có nhiệm vụ cấp độ nào',
    levelUp: 'Lên cấp:',
    levelUpRewards: 'Các phần thưởng lên cấp độ:',
    noRewardsThisLevel: 'Không có phần thưởng nào ở cấp độ này',
    capIncrease: 'Giới hạn +{amount}',
    // Achievements
    loadingAchievements: 'Đang tải các thành tựu...',
    noAchievementsAvailable: 'Không có thành tích nào khả dụng',
    checkBackLater: 'Hãy quay lại sau để có những thử thách mới!',
    claim: 'Thu thập',
    claimReward: 'Nhận phần thưởng',
    claimedOn: 'Đã nhận vào {date}',
    playersUnlocked: '{percent}% số lượng người chơi đã được mở khóa',
    // Level up celebration
    levelUpCelebration: 'LÊN CẤP!',
    // Premium pass
    premiumPassTitle: '{event} vé cao cấp',
    premiumPassUnlockRewards: 'Mở khóa các phần thưởng cao cấp và vật phẩm độc quyền trong sự kiện này',
    premiumPassBenefitPremiumTiers: 'Được hưởng tất cả các phần thưởng cao cấp',
    premiumPassBenefitExclusive: 'Vật phẩm và phần thưởng độc quyền',
    premiumPassBenefitDuration: 'Có hiệu lực trong suốt thời gian diễn ra sự kiện',
    purchasePremiumPass: 'Mua vé cao cấp',
    premiumPassPurchasing: 'Đang thanh toán...',
    cancel: 'Hủy bỏ',
    // Bag full modal
    bagFull: 'Túi đầy',
    bagFullMessage: 'Túi vật phẩm của bạn đã đầy ({current}/{max}). Hãy thu dọn bớt kho lưu trữ trước khi nhận phần thưởng này.',
    goToItems: 'Đi đến Vật phẩm',
    // Time
    hoursLeft: '{hours} giờ nữa',
    minutesLeft: '{minutes} phút nữa',
    secondsLeft: '{seconds} giây nữa',
  },

  // Leaderboard Screen
  leaderboard: {
    title: 'Bảng xếp hạng',
    // Tabs
    territory: 'Lãnh thổ',
    power: 'Sức mạnh',
    alliances: 'Liên minh',
    // Sections
    yourRank: 'Cấp bậc của bạn',
    yourAlliance: 'Liên minh của bạn',
    topAlliances: 'Top 100 Liên minh',
    topByTerritories: 'Top 100 về Lãnh thổ',
    topByGlobalPower: 'Top 100 về Sức mạnh toàn cầu',
    // Quadrants
    global: 'Toàn cầu',
    northWest: 'Tây Bắc',
    northEast: 'Đông Bắc',
    southWest: 'Tây Nam',
    southEast: 'Đông Nam',
    // Stats
    unranked: 'Chưa được xếp hạng',
    territories: 'Lãnh thổ',
    globalPower: 'Sức mạnh toàn cầu',
    gp: 'GP', // there's no way to translate this to vietnamese
    leader: 'Người lãnh đạo: {username}',
    rank: '#{rank}', // uhhhhhhhhhhhhh this does NOT need a translate
    // Loading/error states
    loadingLeaderboard: 'Đang tải bảng xếp hạng...',
    failedToLoad: 'Không thể tải được dữ liệu bảng xếp hạng',
    noDataAvailable: 'Không có dữ liệu bảng xếp hạng có sẵn',
    retry: 'Thử lại',
  },

  // Shop Screen
  shop: {
    title: 'Cửa hàng',
    giftShop: 'Cửa hàng quà tặng',
    // Gift mode
    giftMode: 'Tặng một người bạn',
    exitGiftMode: 'Thoát khỏi chế độ tặng quà',
    giftingTo: 'Tặng đến',
    change: 'Thay đổi',
    selectFriend: 'Chọn một người bạn',
    loadingFriends: 'Đang tải bạn bè',
    noFriendsYet: 'Chưa có bạn bè',
    addFriendsToGift: 'Hãy thêm bạn bè để tặng quà cho họ!',
    friendLevel: 'Cấp độ {level}',
    // Support section
    help: 'Hỗ trợ',
    restoreHint: "Nếu thiếu một số mặt hàng từ một đơn hàng, hãy nhấn bên dưới để khôi phục chúng.",
    restorePurchases: 'Khôi phục các giao dịch mua',
    restoring: 'Đang khôi phục...',
    supportContact: 'Nếu có thêm thắc mắc, vui lòng liên hệ với chúng tôi ở:',
    // Banner detail
    rollOdds: 'Tỉ lệ trúng',
    loadingCharacterData: 'Đang tải dữ liệu nhân vật...',
    availableCharacters: 'Các nhân vật có sẵn',
    loadingCharacters: 'Đang tải các nhân vật...',
    // Rarity
    mythical: 'Thần thoại',
    legendary: 'Huyền thoại',
    epic: 'Sử thi',
    rare: 'Hiếm',
    uncommon: 'Không phổ biến',
    common: 'Thường',
    // Recruit
    recruit: 'TUYỂN',
    inventoryFull: 'Túi đã đầy',
    notEnoughClay: 'Không đủ Đát sét',
    summonCharacter: 'Triệu hồi nhân vật',
    rolling: 'Đang triệu hồi...',
    inventoryFullBanner: 'Túi đã đầy ({current}/{total}) - Hãy mua thêm ô chứa để tăng sức chứa!',
    // Alerts
    errorTitle: 'Lỗi',
    failedToClaimDailyBundle: 'Không thể nhận được gói hằng ngày',
    failedToClaimDailyBundleRetry: 'Không thể nhận được gói hàng ngày. Vui lòng thử lại.',
    notEnoughClayTitle: 'Không đủ Đất sét',
    notEnoughClayMessage: 'Bạn cần {cost} đất sét để mua từ Banner này. Bạn hiện có {current} đất sét.',
    inventoryFullTitle: 'Túi đã đầy',
    inventoryFullMessage: 'Túi của bạn đã đầy ({current}/{total}). Hãy mua thêm ô chứa túi từ cửa hàng để tăng sức chứa!',
    noCharacterReceived: 'Không nhận được nhân vật nào',
    failedToPurchaseFromBanner: 'Mua từ Banner thất bại',
    purchaseFailed: 'Giao dịch thất bại',
    giftFailed: 'Tặng quà thất bại',
    purchaseError: 'Đã xảy ra lỗi trong quá trình thanh toán.',
    giftError: 'Đã xảy ra lỗi trong quá trình tặng quà.',
    upgradeError: 'Đã xảy ra lỗi khi nâng cấp. Vui lòng thử lại.',
    itemBagUpgradeError: 'Đã xảy ra lỗi khi nâng cấp túi vật phẩm. Vui lòng thử lại.',
    restoreComplete: 'Khôi phục hoàn tất',
    restoreCompleteMessage: 'Các giao dịch đã được khôi phục. Nếu bạn bị thiếu vật phẩm, chúng sẽ xuất hiện bây giờ.',
    restoreFailed: 'Khôi phục thất bại',
    restoreFailedMessage: 'Không thể khôi phục giao dịch. Vui lòng thử lại.',
    // Confirmation
    confirmPurchase: 'Xác nhận mua hàng',
    giftTo: 'Gửi {item} đến {username}?',
    purchase: 'Mua',
    sendGift: 'Gửi quà',
    // Success
    purchaseSuccess: 'Mua hàng thành công!',
    giftSent: 'Đã gửi quà!',
    giftSentMessage: '{item} đã được gửi đến {username}!',
    // Bundles section
    bundles: 'Gói vật phẩm',
    loadingBundles: 'Đang tải các gói..',
    dailyBundle: 'Gói hàng ngày',
    dailyBundleDescription: 'Hộp bí ẩn miễn phí hàng ngày với các phần thưởng ngẫu nhiên.',
    free: 'Miễn phí',
    freeBadge: 'MIỄN PHÍ',
    claiming: 'Đang nhận...',
    claim: 'Nhận',
    dailyBundleClaimed: 'Đã nhận gói hàng ngày!',
    // Confirmation modal
    price: 'Giá:',
    youllReceive: "Bạn sẽ nhận được:",
    clay: 'Đất sét',
    gold: 'Vàng',
    influence: 'Sức ảnh hưởng',
    shardlings: 'Mảnh vỡ',
    // Daily Free Clay
    dailyFreeClay: 'Đất sét miễn phí hàng ngày',
    loadingAd: 'Đang tải quảng cáo...',
    watchAdForClay: 'Xem quảng cáo để nhận được +{amount} đất sét!',
    nextRewardIn: 'Phần thưởng tiếp theo sau {time}',
    availableNow: 'Đã có sẵn!',
    rewardClaimed: 'Đã nhận phần thưởng!',
    // Upgrades
    itemBagUpgrade: 'Sức chứa túi vật phẩm của bạn đã tăng thêm {slots} ô!',
  },

  // Auth Screen
  auth: {
    // Language selector
    selectLanguage: 'Chọn ngôn ngữ',
    // OAuth buttons
    continueWithApple: 'Tiếp tục với Apple',
    continueWithGoogle: 'Tiếp tục với Google',
    continueWithDiscord: 'Tiếp tục với Discord',
    continueWithFacebook: 'Tiếp tục với Facebook',
    continueWithPhone: 'Tiếp tục với số điện thoại',
    continueAsGuest: 'Tiếp tục với tư cách Khách',
    signingIn: 'Đang đăng nhập... ',
    creatingAccount: 'Đang tạo tài khoản..',
    or: 'hoặc',
    // Phone step
    enterPhoneNumber: 'Nhập số điện thoại của bạn',
    sendCode: 'Gửi mã',
    sending: 'Đang gửi...',
    backToLoginOptions: 'Quay lại cách tùy chọn đăng nhập',
    // Code step
    enterVerificationCode: 'Nhập mã xác nhận',
    verifyCode: 'Xác nhận mã',
    verifying: 'Đang xác nhận...',
    useDifferentPhone: 'Sử dụng số điện thoại khác',
    // Username step
    chooseUsername: 'Chọn tên người dùng',
    usernameRequirements: '3-15 ký tự, không có dấu cách',
    usernamePlaceholder: 'Tên người dùng',
    completeRegistration: 'Hoàn tất đăng ký',
    creatingAccountButton: 'Đang tạo tài khoản...',
    optional: 'Không bắt buộc',
    referralCodePlaceholder: 'Mã giới thiệu (nếu có)',
    apply: 'Áp dụng ',
    referredBy: 'Được giới thiệu bởi {username}',
    // Terms
    agreeToTerms: 'Tôi đồng ý với',
    termsOfService: 'Điều khoản dịch vụ',
    and: 'và',
    privacyPolicy: 'Chính sách bảo mật',
    acceptTerms: 'Accept Terms',
    acceptTermsApple: 'Bằng cách đăng nhập với Apple, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của chúng tôi.',
    acceptTermsGoogle: 'Bằng cách đăng nhập với Google, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của chúng tôi.',
    acceptTermsDiscord: 'Bằng cách đăng nhập với Discord, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của chúng tôi.',
    acceptTermsFacebook: 'Bằng cách đăng nhập với Facebook, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của chúng tôi.',
    acceptAndContinue: 'Chấp nhận & Tiếp tục',
    // Guest TOS modal
    guestTitle: 'Tiếp tục với tư cách Khách',
    importantNotice: '⚠️ Thông báo quan trọng',
    guestWarning: 'Tài khoản khách là tạm thời và không được sao lưu. Bạn có thể mất tiến trình chơi nếu:',
    guestWarningUninstall: 'Gỡ cài đặt ứng dụng',
    guestWarningClearData: 'Xóa dữ liệu ứng dụng',
    guestWarningSwitch: 'Chuyển thiết bị',
    guestWarningLogout: 'Đăng xuất mà không liên kết tài khoản',
    protectProgress: 'Bảo vệ tiến trình của bạn',
    protectProgressText: 'Bạn có thể liên kết tài khoản khách với số điện thoại hoặc Apple ID bất cứ lúc nào trong Cài đặt để bảo mật tiến trình của mình.',
    yourUsername: 'Tên người dùng của bạn',
    yourUsernameText: 'Tên người dùng của bạn sẽ được tạo tự động và là duy nhất. Bạn có thể thay đổi sau trong Cài đặt.',
    termsAndPrivacy: 'Điều khoản & Bảo mật',
    guestTermsText: 'Bằng cách tiếp tục với tư cách khách, bạn đồng ý với',
    iUnderstand: 'Tôi hiểu rằng tiến trình chơi có thể bị mất',
    creating: 'Đang tạo...',
    // Errors
    pleaseEnterPhone: 'Vui lòng nhập số điện thoại',
    pleaseAgreeToTerms: 'Vui lòng đồng ý với Điều khoản dịch vụ và Chính sách bảo mật',
    pleaseEnterCode: 'Vui lòng nhập mã xác nhận',
    pleaseEnterUsername: 'Vui lòng nhập tên người dùng',
    usernameTooShort: 'Tên người dùng phải có ít nhất 3 ký tự',
    usernameTooLong: 'Tên người dùng không được quá 15 ký tự',
    usernameNoSpaces: 'Tên người dùng không được chứa dấu cách',
    invalidUsername: 'Tên người dùng không hợp lệ',
    networkError: 'Lỗi mạng. Vui lòng thử lại.',
    // Success messages
    appleVerified: 'Apple ID đã được xác nhận. Vui lòng chọn tên người dùng.',
    googleVerified: 'Tài khoản Google đã được xác nhận. Vui lòng chọn tên người dùng.',
    referralApplied: 'Đã áp dụng mã giới thiệu',
    // Referral
    pleaseEnterReferral: 'Vui lòng nhập mã giới thiệu',
    invalidReferralCode: 'Mã giới thiệu không hợp lệ',
  },

  // Loading Screen
  loading: {
    downloadingAssets: 'Đang tải tài nguyên: {done}/{total}',
    takingLonger: 'Quá trình này đang diễn ra lâu hơn bình thường…',
    retry: 'Thử lại',
    // Tips
    tips: {
      tip1: 'Di chuyển quá nhanh có thể làm giảm lượng Đất sét thu thập được — hãy đi chậm lại để thu thập hiệu quả hơn!',
      tip2: 'Bạn có thể rút hoặc chuyển đổi nhân vật đang bảo vệ lãnh thổ từ trang Bộ sưu tập.',
      tip3: "Nhấn vào biểu tượng la bàn để xoay bản đồ theo hướng bạn đang đối mặt.",
      tip4: 'Nhấn vào biểu tượng bản đồ ở góc trên bên phải để xem liên minh nào đang kiểm soát các lãnh thổ lân cận.',
      tip5: 'Chia sẻ Mã bạn bè để thêm bạn và phát triển liên minh toàn cầu của bạn!',
      tip6: 'Sau khi tuyển được nhân vật mới, bạn có thể đặt nhân vật đó làm ảnh đại diện từ Bộ sưu tập.',
      tip7: 'Chinh phục lãnh thổ giúp cả bạn và liên minh tăng thêm sức ảnh hưởng.',
      tip8: 'Nếu bạn rút quân bảo vệ, lãnh thổ vẫn thuộc về bạn nhưng sẽ trở nên dễ bị người khác chiếm đoạt hơn!',
      tip9: 'Hãy giữ an toàn và tôn trọng — không bao giờ xâm phạm trái phép khi thu thập Đất sét hoặc khám phá.',
    },
  },
  // Profile Screen
  profile: {
    // Tabs
    tabs: {
      profile: 'Hồ sơ',
      picture: 'Ảnh đại diện',
      banner: 'Ảnh bìa',
    },
    // Header
    header: {
      close: 'Đóng',
      title: 'Hồ sơ',
    },
    // Artist
    artistLabel: 'Họa sĩ Polandball Go',
    // Profile info
    gp: '{count} GP', // as before, no way of translating this
    level: 'Cấp độ {level}',
    friendCode: 'Mã bạn bè',
    // Referrals
    referrals: 'Giới thiệu',
    checking: 'Đang kiểm tra...',
    friendReferred: 'Đã giới thiệu {count} người bạn',
    friendsReferred: 'Đã giới thiệu {count} người bạn',
    // Social
    connectWith: 'Kết nối với Polandball Go trên:',
    // Redeem code
    redeemCode: 'Đổi mã quà tặng',
    enterCode: 'Nhập mã',
    redeem: 'Đổi mã',
    redeeming: 'Đang đổi...',
    codeRedeemed: 'Đã đổi mã thành công!',
    pleaseEnterCode: 'Vui lòng nhập mã',
    // Empty states
    noCharactersYet: 'Chưa có nhân vật nào! Hãy xoay Banner để bắt đầu xây dựng bộ sưu tập của bạn.',
    loadingCollection: 'Đang tải bộ sưu tập của bạn...',
    // Picture tab
    currentProfilePicture: 'Ảnh đại diện hiện tại',
    chooseProfilePicture: 'Chọn ảnh đại diện',
    selectFromOwned: 'Chọn từ các nhân vật bạn đang hoặc đã từng sở hữu',
    loadingPictures: 'Đang tải các hình ảnh hiện có...',
    loadingProfilePictures: 'Đang tải các ảnh đại diện hiện có...',
    noPicturesAvailable: 'Không có ảnh đại diện nào. Hãy thu thập nhân vật trước!',
    // Banner tab
    currentProfileBanner: 'Ảnh bìa hiện tại',
    chooseProfileBanner: 'Chọn ảnh bìa',
    loadingBanners: 'Đang tải các ảnh bìa hiện có...',
    loadingProfileBanners: 'Đang tải các ảnh bìa hồ sơ hiện có...',
    noBannersAvailable: 'Không có ảnh bìa nào. Hãy thu thập nhân vật trước!',
    currentBadge: 'Hiện tại',
    // Username modal
    editYourName: 'Chỉnh sửa tên',
    enterNewUsername: 'Nhập tên người dùng mới',
    changing: 'Đang thay đổi...',
    // Success popup
    welcome: 'Chào mừng,',
    continue: 'Tiếp tục',
    // Alerts
    copied: 'Đã sao chép',
    friendCodeCopied: 'Đã sao chép mã bạn bè vào bộ nhớ tạm!',
    failedToCopy: 'Không thể sao chép mã bạn bè',
    rewardClaimed: 'Đã nhận phần thưởng',
    cannotClaim: 'Không thể nhận',
    notEligibleYet: 'Bạn chưa đủ điều kiện cho cấp độ này.',
    networkError: 'Lỗi mạng. Vui lòng thử lại.',
    invalidSelection: 'Lựa chọn không hợp lệ',
    canOnlySelectPictures: 'Bạn chỉ có thể chọn ảnh đại diện từ các nhân vật bạn đang hoặc đã từng sở hữu.',
    canOnlySelectBanners: 'Bạn chỉ có thể chọn ảnh bìa từ các nhân vật bạn đang hoặc đã từng sở hữu.',
    updateFailed: 'Cập nhật thất bại',
    failedToUpdatePicture: 'Không thể cập nhật ảnh đại diện',
    failedToUpdateBanner: 'Không thể cập nhật ảnh bìa',
    changeFailed: 'Thay đổi thất bại',
    failedToChangeUsername: 'Không thể thay đổi tên người dùng',
    failedToRedeemCode: 'Không thể đổi mã quà tặng',
    // Validation
    usernameTooShort: 'Tên người dùng phải có ít nhất 3 ký tự',
    usernameTooLong: 'Tên người dùng không được quá 15 ký tự',
    usernameNoSpaces: 'Tên người dùng không được chứa dấu cách',
  },
  friends: {
    // Header
    title: 'Bạn bè',
    // Tabs
    tabs: {
      friends: 'Bạn bè',
      requests: 'Yêu cầu',
      addFriend: 'Thêm bạn',
    },
    // Loading
    loading: 'Đang tải...',
    // Empty states
    noFriendsYet: 'Chưa có bạn bè. Hãy thêm bạn để bắt đầu!',
    noPendingRequests: 'Không có yêu cầu kết bạn nào đang chờ',
    noReferralsYet: 'Chưa có lượt giới thiệu nào. Hãy chia sẻ mã của bạn để mời bạn bè!',
    // Section titles
    friendRequests: 'Yêu cầu kết bạn ({count})',
    sentRequests: 'Yêu cầu đã gửi ({count})',
    yourFriendCode: 'Mã bạn bè của bạn',
    friendCodeSubtitle: 'Sử dụng mã này để nhận thưởng giới thiệu',
    addFriendTitle: 'Thêm bạn bè',
    addFriendSubtitle: 'Nhập mã bạn bè để gửi yêu cầu',
    peopleYouReferred: 'Những người bạn đã giới thiệu ({count})',
    referralsSubtitle: 'Bạn bè đã tham gia bằng mã của bạn',
    // Friend list
    level: 'Cấp {level}',
    levelFull: 'Cấp độ {level}',
    noAlliance: 'Không có liên minh',
    unknownUser: 'Người dùng ẩn danh',
    na: 'N/A', // no way to translate this
    pending: 'Đang chờ',
    // Input
    enterFriendCode: 'Nhập mã bạn bè',
    characterCount: '{count}/8',
    // Button text
    sending: 'Đang gửi...',
    enterMoreCharacters: 'Nhập thêm {count} ký tự',
    enterMoreCharacter: 'Nhập thêm {count} ký tự',
    sendFriendRequest: 'Gửi yêu cầu kết bạn',
    // Alerts - Success
    friendRequestSent: 'Đã gửi yêu cầu kết bạn! 🎉',
    friendRequestSentMessage: "Yêu cầu của bạn đã được gửi thành công. Họ sẽ nhận được thông báo để chấp nhận hoặc từ chối.",
    friendRequestAccepted: 'Đã chấp nhận yêu cầu kết bạn 🎉',
    friendRequestDeclined: 'Đã từ chối yêu cầu kết bạn 👋',
    youHaveActionedRequest: 'Bạn đã {action} yêu cầu kết bạn.',
    accepted: 'chấp nhận',
    declined: 'từ chối',
    friendRemoved: 'Đã xóa bạn bè 👋',
    friendRemovedMessage: '{username} đã được xóa khỏi danh sách bạn bè của bạn.',
    // Alerts - Errors
    friendNotFound: 'Không tìm thấy bạn bè 🔍',
    friendNotFoundMessage: 'Không tìm thấy người chơi nào với mã "{code}". Vui lòng kiểm tra lại mã.',
    alreadyFriends: 'Đã là bạn bè! 👥',
    alreadyFriendsMessage: "Bạn đã là bạn với người chơi này rồi. Hãy kiểm tra danh sách bạn bè.",
    requestAlreadySent: 'Yêu cầu đã được gửi 📤',
    requestAlreadySentMessage: "Bạn đã gửi yêu cầu kết bạn cho người này rồi. Vui lòng đợi họ phản hồi.",
    cantAddYourself: "Không thể tự thêm chính mình 🤔",
    cantAddYourselfMessage: "Bạn không thể gửi yêu cầu kết bạn cho chính mình! Hãy thử nhập một mã khác.",
    unableToSendRequest: 'Không thể gửi yêu cầu',
    connectionError: 'Lỗi kết nối',
    connectionErrorSendMessage: 'Không thể gửi yêu cầu kết bạn. Vui lòng kiểm tra kết nối mạng.',
    unableToProcessRequest: 'Không thể xử lý yêu cầu',
    failedToActionRequest: 'Không thể {action} yêu cầu kết bạn. Vui lòng thử lại.',
    connectionErrorActionMessage: 'Không thể {action} yêu cầu kết bạn. Vui lòng kiểm tra kết nối mạng.',
    // Remove friend
    removeFriend: 'Xóa bạn bè',
    removeFriendConfirm: 'Bạn có chắc chắn muốn xóa {username} khỏi danh sách bạn bè?',
    cancel: 'Hủy',
    remove: 'Xóa',
    unableToRemoveFriend: 'Không thể xóa bạn bè',
    failedToRemoveFriend: 'Xóa bạn bè thất bại. Vui lòng thử lại.',
    connectionErrorRemoveMessage: 'Không thể xóa bạn bè. Vui lòng kiểm tra kết nối mạng.',
  copied: 'Đã sao chép',
    friendCodeCopied: 'Đã sao chép mã bạn bè vào bộ nhớ tạm!',
    error: 'Lỗi',
    failedToCopy: 'Không thể sao chép mã bạn bè',
    // Share
    shareMessage: 'Tham gia cùng mình trong Polandball Go! Tải trò chơi tại: {downloadLink}\nMã bạn bè của tôi là: {friendCode}',
    shareTitle: 'Lời mời Polandball Go',
  },
  territories: {
    // Header
    title: 'Lãnh thổ của tôi',
    // Info
    infoText: 'Nhấn vào một lãnh thổ để xem trên bản đồ',
    tapToView: 'Nhấn để xem trên bản đồ',
    // Default name
    unnamedLand: 'Vùng đất chưa đặt tên',
    // Filter options
    filterAll: 'Tất cả',
    filterDefended: 'Đang bảo vệ',
    filterUndefended: 'Không bảo vệ',
    // Sort options
    sortRecent: 'Gần đây',
    sortCp: 'CP',
    sortDistance: 'Khoảng cách',
    // Withdraw All
    withdrawAll: 'Rút tất cả',
    // Loading
    loadingTerritories: 'Đang tải lãnh thổ...',
    loadingMore: 'Đang tải thêm...',
    // Empty states
    noTerritoriesYet: 'Chưa có lãnh thổ nào',
    captureTerritoriesHint: 'Hãy chiếm lãnh thổ bằng cách triển khai nhân vật trên bản đồ!',
    noTerritoriesMatchFilter: 'Không có lãnh thổ nào khớp với bộ lọc',
    adjustFilterHint: 'Hãy thử điều chỉnh cài đặt bộ lọc của bạn',
    // Territory card
    enterName: 'Nhập tên...',
    heldFor: 'Đã giữ trong',
    // Time formatting
    minute: '{count} phút',
    minutes: '{count} phút',
    hour: '{count} giờ',
    hours: '{count} giờ',
    day: '{count} ngày',
    days: '{count} ngày',
    // Defender actions
    swap: 'Đổi',
    withdraw: 'Rút quân',
    swapDefender: 'Đổi quân bảo vệ',
    // End of list
    allTerritoriesLoaded: 'Đã tải tất cả {count} lãnh thổ',
    // Alerts - Success
    success: 'Thành công',
    withdrawnCount: 'Đã rút {count} nhân vật khỏi lãnh thổ của bạn.',
    // Alerts - Errors
    error: 'Lỗi',
    failedToLoadCharacters: 'Không thể tải nhân vật của bạn',
    failedToSwapDefender: 'Không thể đổi quân bảo vệ',
    failedToWithdrawCharacter: 'Không thể rút quân',
    failedToWithdrawCharacters: 'Không thể rút quân. Vui lòng thử lại.',
    invalidName: 'Tên không hợp lệ',
    nameTooShort: 'Tên lãnh thổ phải có ít nhất 3 ký tự.',
    notAuthenticated: 'Chưa xác thực',
    inappropriateName: 'Tên không phù hợp',
    inappropriateNameMessage: 'Vui lòng chọn một tên khác. Tên này chứa ngôn từ không phù hợp.',
    failedToRename: 'Không thể đổi tên lãnh thổ. Vui lòng thử lại.',
    failedToUpdateLock: 'Không thể cập nhật trạng thái khóa',
    failedToUpdateLockRetry: 'Không thể cập nhật trạng thái khóa. Vui lòng thử lại.',
  },
  quickDeploy: {
    // Territory name
    unnamedLand: 'Lãnh thổ không tên',
    enterName: 'Nhập tên...',
    // Defender display
    unknown: 'Không xác định',
    undefended: 'Không có bảo vệ',
    deploying: 'Đang triển khai...',
    // Tabs
    tabContest: 'Tranh giành',
    tabDefend: 'Bảo vệ',
    tabDeploy: 'Triển khai',
    tabSynergy: 'Hiệp lực',
    // Instructions
    tapToSwap: 'Nhấn để đổi',
    tapToContest: 'Nhấn để tranh giành',
    tapToDeploy: 'Nhấn để triển khai',
    tapToWithdraw: 'Nhấn để rút quân',
    // Empty/Loading states
    noCharactersAvailable: 'Không có nhân vật nào khả dụng',
    allDeployed: 'Tất cả đã được triển khai',
    loading: 'Đang tải...',
    // Alerts - Errors
    error: 'Lỗi',
    invalidName: 'Tên không hợp lệ',
    nameTooShort: 'Tên lãnh thổ phải có ít nhất 3 ký tự.',
    notAuthenticated: 'Chưa xác thực',
    inappropriateName: 'Tên không phù hợp',
    inappropriateNameMessage: 'Vui lòng chọn một tên khác. Tên này chứa ngôn từ không phù hợp.',
    failedToRename: 'Không thể đổi tên lãnh thổ. Vui lòng thử lại.',
  },

  // Tutorials
  tutorials: {
    // TutorialsModal
    close: 'Đóng',
    title: 'Hướng dẫn',
    replayTutorials: 'Xem lại hướng dẫn',
    reviewMechanics: 'Xem lại cơ chế trò chơi bất cứ khi nào bạn cần',
    // Tutorial list items
    basicTutorial: 'Hướng dẫn cơ bản',
    basicTutorialDesc: 'Tìm hiểu những điều cơ bản để bắt đầu với Polandball Go',
    territoryTutorial: 'Hướng dẫn lãnh thổ',
    territoryTutorialDesc: 'Tìm hiểu về lãnh thổ, triển khai quân và thu thập sức ảnh hưởng',
    menuTutorial: 'Hướng dẫn Menu',
    menuTutorialDesc: 'Tìm hiểu về Menu và tất cả các tính năng có sẵn',
    powerUpTutorial: 'Hướng dẫn tăng sức mạnh',
    powerUpTutorialDesc: 'Tìm hiểu cách tăng cấp và tăng hạng cho nhân vật của bạn',
    xpTutorial: 'Hướng dẫn XP & Cấp độ',
    xpTutorialDesc: 'Tìm hiểu cách hoạt động của XP và cách tăng cấp trên 10',
    socialTutorial: 'Hướng dẫn Bạn bè & Liên minh',
    socialTutorialDesc: 'Tìm hiểu cách thêm bạn bè và tham gia liên minh',
    // InteractiveTutorial - Initial tutorial
    welcomeTitle: 'Chào mừng đến với Polandball Go!',
    welcomeDesc: "Hãy bắt đầu hành trình chinh phục thế giới của bạn ngay bây giờ!",
    collectClayTitle: 'Thu thập Đất sét',
    collectClayDesc: 'Nhấn vào khối đất sét bên dưới để nhận 1000 đất sét!',
    exploreTitle: 'Khám phá thế giới',
    exploreDesc: 'Di chuyển ngoài đời thực để di chuyển trên bản đồ. Hãy đến gần đất sét trong phạm vi 50 mét để thu thập!',
    recruitTitle: 'Tuyển nhân vật đầu tiên',
    recruitDesc: 'Bạn có thể dùng Đất sét để triệu hồi Nhân vật từ tab "Tuyển".',
    questsTitle: 'Hoàn thành nhiệm vụ để thăng tiến',
    questsDesc: 'Xem nhiệm vụ để nhận phần thưởng hàng ngày và lên cấp!',
    // InteractiveTutorial - Level 2 tutorial
    territoryConquestTitle: 'Chinh phục lãnh thổ',
    territoryConquestDesc: 'Bây giờ bạn đã tuyển được nhân vật đầu tiên, đã đến lúc bắt đầu chinh phục.',
    territoryOwnershipTitle: 'Quyền sở hữu lãnh thổ',
    territoryOwnershipDesc: "Đây là ba loại lãnh thổ bạn sẽ gặp:",
    deployAction: 'Triển khai',
    deployActionDesc: 'bất kỳ nhân vật nào để chiếm đóng lãnh thổ chưa có chủ.',
    contestAction: 'Tranh giành',
    contestActionDesc: 'lãnh thổ của đối phương bằng một nhân vật mạnh hơn để chiếm đất của họ.',
    defendAction: 'Bảo vệ',
    defendActionDesc: 'một lãnh thổ của đồng minh bằng nhân vật của bạn để giữ an toàn.',
    defendedVsUndefendedTitle: 'Được bảo vệ vs Không bảo vệ',
    defendedVsUndefendedDesc: 'Bạn có thể rút quân bảo vệ để sử dụng ở nơi khác.\n\nLãnh thổ vẫn là của bạn, nhưng sẽ trở thành "không bảo vệ" và dễ bị người khác chiếm đoạt!',
    earnInfluenceTitle: 'Kiếm Sức ảnh hưởng',
    earnInfluenceDesc: 'Mỗi lãnh thổ bạn kiểm soát sẽ tạo ra Sức ảnh hưởng theo thời gian. Hãy thu thập thường xuyên để thăng cấp nhân vật và mạnh mẽ hơn!',
    influence: 'Sức ảnh hưởng',
    perHour: '+5 mỗi giờ',
    mapControlsTitle: 'Điều khiển bản đồ',
    mapControlsDesc: 'Sử dụng các nút này để điều hướng và khám phá:',
    recenter: 'Định vị lại:',
    recenterDesc: 'Nhấn để quay lại vị trí hiện tại của bạn',
    territoryView: 'Chế độ xem lãnh thổ:',
    territoryViewDesc: 'Kéo và thả để xem các lãnh thổ đang sở hữu',
    // InteractiveTutorial - Menu tutorial
    menuTitle: 'Menu',
    menuDesc: 'Truy cập tất cả các tính năng từ nút Menu ở góc dưới bên phải.',
    menuOptionsTitle: 'Các tùy chọn Menu',
    menuOptionsDesc: "Đây là chức năng của từng mục:",
    myBalls: 'Countryballs của tôi:',
    myBallsDesc: 'Xem và quản lý tất cả các Nhân vật bạn đã tuyển',
    shop: 'Cửa hàng:',
    shopDesc: 'Mua vật phẩm, gói quà và tiền tệ cao cấp',
    items: 'Vật phẩm:',
    itemsDesc: 'Sử dụng Thuốc và các vật phẩm tiêu hao khác từ túi đồ',
    dex: 'Dex:',
    dexDesc: 'Theo dõi tiến trình thu thập tất cả các Nhân vật trong trò chơi',
    settings: 'Cài đặt:',
    settingsDesc: 'Quản lý tài khoản và tùy chỉnh trò chơi',
    // InteractiveTutorial - Powerup tutorial
    powerUpTitle: 'Tăng sức mạnh cho nhân vật',
    powerUpDesc: 'Làm cho nhân vật mạnh hơn thông qua việc Lên cấp và Tăng hạng!\n\nTruy cập các tùy chọn này từ mục "Countryballs của tôi".',
    levelUpTitle: 'Lên cấp',
    levelUpDesc: "Tăng cấp độ nhân vật để gia tăng Lực chiến (CP).",
    levelUp: 'Lên cấp',
    levelUpExplanation: 'Sức ảnh hưởng',
    levelUpExplanationText: 'là cần thiết để tăng cấp cho nhân vật của bạn',
    level: 'Cấp độ',
    rankUpTitle: 'Tăng hạng',
    rankUpDesc: 'Dùng các nhân vật trùng lặp để tăng số sao và mở khóa tiềm năng CP cao hơn.',
    rankUp: 'Tăng hạng',
    rankUpExplanation: 'Mỗi nhân vật bạn dùng để nâng cấp sẽ tặng một lượng',
    shards: 'Mảnh vỡ',
    rankUpExplanationEnd: 'tùy thuộc vào thứ hạng của nó.',
    // InteractiveTutorial - Social tutorial
    friendsAlliancesTitle: 'Bạn bè & Liên minh',
    friendsAlliancesDesc: 'Kết nối với những người chơi khác để mở khóa các tính năng cộng đồng!\n\nNhấn vào nút Liên minh ở bên trái để bắt đầu.',
    friendCodeTitle: 'Mã bạn bè của bạn',
    friendCodeDesc: 'Mỗi người chơi có một Mã bạn bè duy nhất. Hãy chia sẻ mã của bạn để họ có thể thêm bạn!',
    yourFriendCode: 'Mã bạn bè của bạn',
    friendCodeHint: 'Tìm mã của bạn trong Hồ sơ hoặc màn hình Bạn bè',
    sendRequestsTitle: 'Gửi yêu cầu kết bạn',
    sendRequestsDesc: 'Bạn cũng có thể gửi yêu cầu bằng cách xem hồ sơ người khác và nhấn nút "Thêm".',
    playerName: 'Tên người chơi',
    add: 'Thêm',
    viewProfileHint: 'Nhấn vào người chơi trong Bảng xếp hạng hoặc danh sách Liên minh để xem hồ sơ của họ.',
    joinAllianceTitle: 'Tham gia liên minh',
    joinAllianceDesc: 'Liên minh giúp bạn tăng sức ảnh hưởng ngoài sức ảnh hưởng cá nhân.',
    browseAlliances: 'Duyệt liên minh',
    createAlliance: 'Tạo liên minh',
    browseAlliancesHint: 'các liên minh công khai và yêu cầu tham gia',
    createAllianceHint: 'liên minh của riêng bạn và mời bạn bè',
    chatWithAlliance: 'Trò chuyện với thành viên và cùng nhau thi đấu',
    // InteractiveTutorial - XP tutorial
    xpLevelsTitle: 'XP & Cấp độ',
    xpLevelsDesc: "Bắt đầu từ cấp 11, bạn sẽ cần XP (Điểm kinh nghiệm) để lên cấp.",
    howToEarnXpTitle: 'Cách kiếm XP',
    howToEarnXpDesc: 'Đây là các cách chính để nhận XP:',
    collectClay: 'Thu thập đất sét:',
    collectClayXpDesc: 'Số lượng càng lớn nhận được càng nhiều XP.',
    recruitCharacters: 'Tuyển nhân vật:',
    recruitCharactersXpDesc: 'Nhân vật càng hiếm nhận được càng nhiều XP.',
    conquerBattle: 'Chinh phục & Chiến đấu:',
    conquerBattleXpDesc: 'Nhận XP mỗi khi bạn chiếm được một lãnh thổ.',
    rankUpBalls: 'Tăng hạng nhân vật:',
    rankUpBallsXpDesc: 'Hạng càng cao nhận được càng nhiều XP.',
    // Buttons
    next: 'Tiếp theo',
    gotIt: 'Đã hiểu!',
  },
} as const;

// Helper type to convert readonly literal types to string
type DeepStringify<T> = {
  [K in keyof T]: T[K] extends object ? DeepStringify<T[K]> : string;
};

export type TranslationKeys = DeepStringify<typeof en>;

